services:
  php:
    image: php:8.3-apache
    container_name: ETS-Dubuis_php8_3
    ports:
      - "8010:80" # on définit le port pour accéder à l'application (localhost:8007)
    volumes:
      - ./src:/var/www/html # on monte le dossier courant dans le dossier /var/www/html du container
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: mysql:8.0
    container_name: ETS-Dubuis_mysql8_0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ETS-Dubuis
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3311:3311"
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: ETS-Dubuis_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 20M
    ports:
      - "8090:80" # on définit le port pour accéder à phpmyadmin (localhost:8087)
